### ISSUE TITLE
CLI options?

### ISSUE THREAD

**Issue by secretnumber** [mycroft/chainstate#19]
Great tool, thank you for this!

Is there a way to give arguments via cli to only output the addresses and amounts, as opposed to the whole thing?

And perhaps pointing to the chainstate location instead of copying it to the script first?

Sorry, I don't know C++, or programming in general that well to understand all the files.

Thanks.

**Comment by mycroft** [comment]
@secretnumber Copying the chainstate is required because for some reason, and despite the fact chainstate doesn't modify the database, the wallet won't want to reuse it after having used chainstate against it. I still need to find out why.

I think the whole tool would require a lot of rewrite, and may be some day I'll take some time to add arguments & customization... but so far, it is a crappy hack... sorry for that!
